export const FINAL_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: { revoke: 'Revoke', rotate: 'Rotate', requestTime: 'Time', requestAction: 'Action', requestTarget: 'Target', requestDecision: 'Decision', requestOutcome: 'Outcome', requestId: 'Request ID', evaluate: 'Evaluate', client: 'Client', capability: 'Capability', mutationRequest: 'Mutation request', noClientsIssued: 'No clients issued yet.', issueObserverClient: 'Issue observer client', tokenShownOnce: 'The token will be shown once after creation.' },
  es: { revoke: 'Revocar', rotate: 'Rotar', requestTime: 'Hora', requestAction: 'Acción', requestTarget: 'Objetivo', requestDecision: 'Decisión', requestOutcome: 'Resultado', requestId: 'ID de solicitud', evaluate: 'Evaluar', client: 'Cliente', capability: 'Capability', mutationRequest: 'Solicitud de mutación', noClientsIssued: 'Todavía no se ha emitido ningún cliente.', issueObserverClient: 'Emitir cliente observer', tokenShownOnce: 'El token se mostrará una sola vez después de la creación.' },
  fr: { revoke: 'Révoquer', rotate: 'Faire pivoter', requestTime: 'Heure', requestAction: 'Action', requestTarget: 'Cible', requestDecision: 'Décision', requestOutcome: 'Résultat', requestId: 'ID de requête', evaluate: 'Évaluer', client: 'Client', capability: 'Capability', mutationRequest: 'Requête de mutation', noClientsIssued: 'Aucun client n’a encore été émis.', issueObserverClient: 'Émettre un client observer', tokenShownOnce: 'Le jeton ne sera affiché qu’une fois après la création.' },
  de: { revoke: 'Widerrufen', rotate: 'Rotieren', requestTime: 'Zeit', requestAction: 'Aktion', requestTarget: 'Ziel', requestDecision: 'Entscheidung', requestOutcome: 'Ergebnis', requestId: 'Anforderungs-ID', evaluate: 'Auswerten', client: 'Client', capability: 'Capability', mutationRequest: 'Änderungsanfrage', noClientsIssued: 'Noch keine Clients ausgestellt.', issueObserverClient: 'Observer-Client ausstellen', tokenShownOnce: 'Das Token wird nach der Erstellung nur einmal angezeigt.' },
  pt: { revoke: 'Revogar', rotate: 'Rotacionar', requestTime: 'Hora', requestAction: 'Ação', requestTarget: 'Alvo', requestDecision: 'Decisão', requestOutcome: 'Resultado', requestId: 'ID da solicitação', evaluate: 'Avaliar', client: 'Cliente', capability: 'Capability', mutationRequest: 'Solicitação de mutação', noClientsIssued: 'Nenhum cliente foi emitido ainda.', issueObserverClient: 'Emitir cliente observer', tokenShownOnce: 'O token será exibido uma única vez após a criação.' },
  it: { revoke: 'Revoca', rotate: 'Ruota', requestTime: 'Ora', requestAction: 'Azione', requestTarget: 'Destinazione', requestDecision: 'Decisione', requestOutcome: 'Risultato', requestId: 'ID richiesta', evaluate: 'Valuta', client: 'Client', capability: 'Capability', mutationRequest: 'Richiesta di mutazione', noClientsIssued: 'Nessun client emesso.', issueObserverClient: 'Emetti client observer', tokenShownOnce: 'Il token verrà mostrato una sola volta dopo la creazione.' },
  zh: { revoke: '撤销', rotate: '轮换', requestTime: '时间', requestAction: '操作', requestTarget: '目标', requestDecision: '决策', requestOutcome: '结果', requestId: '请求 ID', evaluate: '评估', client: '客户端', capability: 'Capability', mutationRequest: '修改请求', noClientsIssued: '尚未签发客户端。', issueObserverClient: '签发 Observer 客户端', tokenShownOnce: '令牌创建后只显示一次。' },
  ja: { revoke: '失効', rotate: 'ローテーション', requestTime: '時刻', requestAction: 'アクション', requestTarget: '対象', requestDecision: '判定', requestOutcome: '結果', requestId: 'リクエスト ID', evaluate: '評価', client: 'クライアント', capability: 'Capability', mutationRequest: '変更リクエスト', noClientsIssued: '発行済みクライアントはありません。', issueObserverClient: 'Observer クライアントを発行', tokenShownOnce: 'トークンは作成後に一度だけ表示されます。' },
  ru: { revoke: 'Отозвать', rotate: 'Ротировать', requestTime: 'Время', requestAction: 'Действие', requestTarget: 'Цель', requestDecision: 'Решение', requestOutcome: 'Результат', requestId: 'ID запроса', evaluate: 'Оценить', client: 'Клиент', capability: 'Возможность', mutationRequest: 'Запрос на изменение', noClientsIssued: 'Клиенты ещё не выпущены.', issueObserverClient: 'Выпустить клиента observer', tokenShownOnce: 'Токен будет показан только один раз после создания.' },
  hi: { revoke: 'रद्द करें', rotate: 'रोटेट करें', requestTime: 'समय', requestAction: 'कार्रवाई', requestTarget: 'लक्ष्य', requestDecision: 'निर्णय', requestOutcome: 'परिणाम', requestId: 'अनुरोध ID', evaluate: 'मूल्यांकन करें', client: 'क्लाइंट', capability: 'क्षमता', mutationRequest: 'Mutation अनुरोध', noClientsIssued: 'अभी कोई क्लाइंट जारी नहीं हुआ।', issueObserverClient: 'Observer क्लाइंट जारी करें', tokenShownOnce: 'टोकन बनने के बाद केवल एक बार दिखाया जाएगा।' },
  ar: { revoke: 'إلغاء', rotate: 'تدوير', requestTime: 'الوقت', requestAction: 'الإجراء', requestTarget: 'الهدف', requestDecision: 'القرار', requestOutcome: 'النتيجة', requestId: 'معرّف الطلب', evaluate: 'تقييم', client: 'العميل', capability: 'القدرة', mutationRequest: 'طلب تعديل', noClientsIssued: 'لم يتم إصدار أي عميل بعد.', issueObserverClient: 'إصدار عميل Observer', tokenShownOnce: 'سيُعرض الرمز مرة واحدة بعد الإنشاء.' },
};
