const names = ['Inventory', 'States', 'Automations', 'Configuration', 'Services', 'Events', 'History', 'Logbook', 'Devices', 'Areas', 'Floors', 'Labels', 'EntityRegistry', 'Scripts', 'Scenes', 'Helpers', 'Integrations', 'GatewayPorts'];
const packs = ['Basic', 'Automation', 'Mcp', 'Completeness'];
const specs: Record<string, { dev: string[]; labels: string[]; descriptions: string[]; packLabels: string[]; packDescriptions: string[]; status: string[] }> = {
  de: { dev: ['Upstream-Status','Entitäts-ID, z. B. light.kitchen','Startzeit, z. B. 2026-08-01T00:00:00Z','Elemente','ms','Schema geändert','Regressionen','Nicht überprüfbar','Lokaler Listener','HTTP-Gesundheitsstatus','HTTP-MCP','Veröffentlichung des Host-Ports'], labels: ['Bestand','Zustände','Automationen','Konfiguration und Register','Dienstekatalog','Ereigniskatalog','Verlauf','Logbuch','Geräteregister','Bereichsregister','Etagenregister','Labelregister','Entitätsregister','Skripte','Szenen','Helfer','Integrationen','Gateway-Ports und MCP-Transport'], descriptions: ['Entitäten und Bestandszahlen lesen','Aktuelle Zustände und Attribute lesen','Automationsentitäten und ihren Zustand lesen','Konfiguration und Registermetadaten lesen','Verfügbare Dienste und Schemata lesen','Verfügbare Home-Assistant-Ereignisse lesen','Zustandsverlauf mit optionalen Filtern lesen','Aktivitätsprotokoll mit optionalen Filtern lesen','Registrierte Geräte lesen','Registrierte Bereiche lesen','Registrierte Etagen lesen','Registrierte Labels lesen','Registrierte Entitäten und Metadaten lesen','Skriptentitäten lesen','Szenenentitäten lesen','Eingabehelfer lesen','Integrationsdomänen lesen','Lokalen Listener und MCP-Authentifizierung prüfen'], packLabels: ['Grundinventar','Automationsdiagnose','MCP-Bereitschaft','Datenvollständigkeit'], packDescriptions: ['Kernmodell und Register.','Automationen und Aktivitätsdaten.','Ressourcen für Observer-Clients.','Erweiterte Abdeckung und explizite Endpunktfehler.'], status: ['OK','Fehler','Teilweise','Bereit','Wird geladen','Unbekannt'] },
  pt: { dev: ['Estado do upstream','ID da entidade, por exemplo light.cozinha','Hora de início, por exemplo 2026-08-01T00:00:00Z','itens','ms','esquema alterado','regressões','Não verificável','Listener local','Saúde HTTP','MCP HTTP','Publicação da porta do anfitrião'], labels: ['Inventário de entidades','Estados das entidades','Automações','Configuração e registos','Catálogo de serviços','Catálogo de eventos','Histórico','Livro de registos','Registo de dispositivos','Registo de áreas','Registo de pisos','Registo de etiquetas','Registo de entidades','Scripts','Cenas','Ajudantes','Integrações','Portas do gateway e transporte MCP'], descriptions: ['Ler entidades e contagens do inventário','Ler estados e atributos atuais','Ler entidades de automação e estado','Ler configuração e metadados de registos','Ler serviços e esquemas disponíveis','Ler eventos disponíveis','Ler histórico com filtros opcionais','Ler atividade com filtros opcionais','Ler dispositivos registados','Ler áreas registadas','Ler pisos registados','Ler etiquetas registadas','Ler entidades e metadados','Ler entidades de script','Ler entidades de cena','Ler ajudantes de entrada','Ler domínios de integração','Verificar listener local e autenticação MCP'], packLabels: ['Inventário básico','Diagnóstico de automações','Preparação MCP','Completude dos dados'], packDescriptions: ['Modelo de leitura e registos principais.','Automações e dados de atividade.','Recursos para clientes observer.','Cobertura alargada e falhas explícitas.'], status: ['OK','Erro','Parcial','Pronto','A carregar','Desconhecido'] },
  it: { dev: ['Stato upstream','ID entità, ad esempio light.cucina','Ora di inizio, ad esempio 2026-08-01T00:00:00Z','elementi','ms','schema modificato','regressioni','Non verificabile','Listener locale','Salute HTTP','MCP HTTP','Pubblicazione della porta host'], labels: ['Inventario entità','Stati entità','Automazioni','Configurazione e registri','Catalogo servizi','Catalogo eventi','Cronologia','Registro attività','Registro dispositivi','Registro aree','Registro piani','Registro etichette','Registro entità','Script','Scene','Helper','Integrazioni','Porte gateway e trasporto MCP'], descriptions: ['Leggi entità e conteggi inventario','Leggi stati e attributi correnti','Leggi entità e stato delle automazioni','Leggi configurazione e metadati','Leggi servizi e schemi disponibili','Leggi eventi disponibili','Leggi cronologia con filtri opzionali','Leggi attività con filtri opzionali','Leggi dispositivi registrati','Leggi aree registrate','Leggi piani registrati','Leggi etichette registrate','Leggi entità e metadati','Leggi entità script','Leggi entità scena','Leggi helper di input','Leggi domini di integrazione','Verifica listener locale e autenticazione MCP'], packLabels: ['Inventario di base','Diagnostica automazioni','Preparazione MCP','Completezza dei dati'], packDescriptions: ['Modello di lettura e registri principali.','Automazioni e dati di attività.','Risorse per client observer.','Copertura estesa ed errori espliciti.'], status: ['OK','Errore','Parziale','Pronto','Caricamento','Sconosciuto'] },
  zh: { dev: ['上游状态','实体 ID，例如 light.kitchen','开始时间，例如 2026-08-01T00:00:00Z','项','毫秒','架构已变化','回归','无法验证','本地监听器','HTTP 健康状态','HTTP MCP','主机端口发布'], labels: ['实体清单','实体状态','自动化','配置与注册表','服务目录','事件目录','历史','日志簿','设备注册表','区域注册表','楼层注册表','标签注册表','实体注册表','脚本','场景','辅助实体','集成','网关端口与 MCP 传输'], descriptions: ['读取实体和清单计数','读取当前状态和属性','读取自动化实体及状态','读取配置和注册表元数据','读取可用服务和模式','读取可用事件类型','读取状态历史及可选筛选','读取活动记录及可选筛选','读取已注册设备','读取已注册区域','读取已注册楼层','读取已注册标签','读取实体及元数据','读取脚本实体','读取场景实体','读取输入辅助实体','读取集成域','检查本地监听器和 MCP 认证'], packLabels: ['基础清单','自动化诊断','MCP 就绪','数据完整性'], packDescriptions: ['核心读取模型和注册表。','自动化及相关活动数据。','Observer 客户端所需资源。','扩展数据覆盖和明确的端点失败。'], status: ['正常','错误','部分成功','就绪','加载中','未知'] },
  ja: { dev: ['上流ステータス','エンティティ ID（例: light.kitchen）','開始時刻（例: 2026-08-01T00:00:00Z）','件','ミリ秒','スキーマが変更されました','回帰','検証不可','ローカルリスナー','HTTP ヘルス','HTTP MCP','ホストポート公開'], labels: ['エンティティ一覧','エンティティ状態','オートメーション','設定とレジストリ','サービス一覧','イベント一覧','履歴','ログブック','デバイスレジストリ','エリアレジストリ','フロアレジストリ','ラベルレジストリ','エンティティレジストリ','スクリプト','シーン','ヘルパー','インテグレーション','ゲートウェイポートと MCP トランスポート'], descriptions: ['エンティティと件数を取得','現在の状態と属性を取得','オートメーションの状態を取得','設定とレジストリのメタデータを取得','利用可能なサービスとスキーマを取得','利用可能なイベントを取得','状態履歴を取得（任意の絞り込み）','活動記録を取得（任意の絞り込み）','登録済みデバイスを取得','登録済みエリアを取得','登録済みフロアを取得','登録済みラベルを取得','登録済みエンティティを取得','スクリプトエンティティを取得','シーンエンティティを取得','入力ヘルパーを取得','統合ドメインを取得','ローカルリスナーと MCP 認証を確認'], packLabels: ['基本インベントリ','オートメーション診断','MCP 準備状況','データ完全性'], packDescriptions: ['基本の読み取りモデルとレジストリ。','オートメーションと関連活動データ。','Observer クライアントに必要なリソース。','拡張データ範囲と明示的なエラー。'], status: ['正常','エラー','一部成功','準備完了','読み込み中','不明'] },
  ru: { dev: ['Состояние upstream','ID сущности, например light.kitchen','Время начала, например 2026-08-01T00:00:00Z','элементов','мс','схема изменена','регрессий','Невозможно проверить','Локальный слушатель','Состояние HTTP','HTTP MCP','Публикация порта хоста'], labels: ['Инвентарь сущностей','Состояния сущностей','Автоматизации','Конфигурация и реестры','Каталог сервисов','Каталог событий','История','Журнал','Реестр устройств','Реестр зон','Реестр этажей','Реестр меток','Реестр сущностей','Скрипты','Сцены','Помощники','Интеграции','Порты шлюза и транспорт MCP'], descriptions: ['Получение сущностей и счётчиков','Получение текущих состояний и атрибутов','Получение автоматизаций и их состояний','Получение конфигурации и метаданных','Получение доступных сервисов и схем','Получение доступных событий','Получение истории с фильтрами','Получение записей активности с фильтрами','Получение зарегистрированных устройств','Получение зарегистрированных зон','Получение зарегистрированных этажей','Получение зарегистрированных меток','Получение сущностей и метаданных','Получение скриптов','Получение сцен','Получение помощников','Получение доменов интеграций','Проверка локального слушателя и аутентификации MCP'], packLabels: ['Базовый инвентарь','Диагностика автоматизаций','Готовность MCP','Полнота данных'], packDescriptions: ['Основная модель чтения и реестры.','Автоматизации и данные активности.','Ресурсы для клиентов observer.','Расширенное покрытие и явные ошибки.'], status: ['Успешно','Ошибка','Частично','Готово','Загрузка','Неизвестно'] },
  hi: { dev: ['अपस्ट्रीम स्थिति','एंटिटी ID, जैसे light.kitchen','प्रारंभ समय, जैसे 2026-08-01T00:00:00Z','आइटम','मिलीसेकंड','स्कीमा बदल गया','रिग्रेशन','सत्यापित नहीं किया जा सकता','स्थानीय listener','HTTP स्वास्थ्य','HTTP MCP','होस्ट पोर्ट प्रकाशन'], labels: ['एंटिटी इन्वेंटरी','एंटिटी स्थितियाँ','ऑटोमेशन','कॉन्फ़िगरेशन और रजिस्ट्री','सेवा कैटलॉग','इवेंट कैटलॉग','इतिहास','लॉगबुक','डिवाइस रजिस्ट्री','एरिया रजिस्ट्री','फ़्लोर रजिस्ट्री','लेबल रजिस्ट्री','एंटिटी रजिस्ट्री','स्क्रिप्ट','सीन','हेल्पर','इंटीग्रेशन','गेटवे पोर्ट और MCP ट्रांसपोर्ट'], descriptions: ['एंटिटी और इन्वेंटरी गिनती पढ़ें','वर्तमान स्थितियाँ और गुण पढ़ें','ऑटोमेशन की स्थिति पढ़ें','कॉन्फ़िगरेशन मेटाडेटा पढ़ें','उपलब्ध सेवाएँ और स्कीमा पढ़ें','उपलब्ध इवेंट पढ़ें','वैकल्पिक फ़िल्टर के साथ इतिहास पढ़ें','वैकल्पिक फ़िल्टर के साथ गतिविधि पढ़ें','पंजीकृत डिवाइस पढ़ें','पंजीकृत एरिया पढ़ें','पंजीकृत फ़्लोर पढ़ें','पंजीकृत लेबल पढ़ें','पंजीकृत एंटिटी और मेटाडेटा पढ़ें','स्क्रिप्ट एंटिटी पढ़ें','सीन एंटिटी पढ़ें','इनपुट हेल्पर पढ़ें','इंटीग्रेशन डोमेन पढ़ें','स्थानीय listener और MCP प्रमाणीकरण जाँचें'], packLabels: ['बेसिक इन्वेंटरी','ऑटोमेशन डायग्नोस्टिक्स','MCP तैयारी','डेटा पूर्णता'], packDescriptions: ['मुख्य रीड मॉडल और रजिस्ट्री।','ऑटोमेशन और गतिविधि डेटा।','Observer क्लाइंट के लिए संसाधन।','विस्तृत कवरेज और स्पष्ट endpoint त्रुटियाँ।'], status: ['ठीक','त्रुटि','आंशिक','तैयार','लोड हो रहा है','अज्ञात'] },
  ar: { dev: ['حالة المنبع','معرّف الكيان، مثل light.kitchen','وقت البدء، مثل 2026-08-01T00:00:00Z','العناصر','مللي ثانية','تغيّر المخطط','تراجعات','غير قابل للتحقق','المستمع المحلي','سلامة HTTP','MCP عبر HTTP','نشر منفذ المضيف'], labels: ['جرد الكيانات','حالات الكيانات','الأتمتة','الإعداد والسجلات','كتالوج الخدمات','كتالوج الأحداث','السجل التاريخي','سجل الأنشطة','سجل الأجهزة','سجل المناطق','سجل الطوابق','سجل التسميات','سجل الكيانات','البرامج النصية','المشاهد','المساعدات','التكاملات','منافذ البوابة ونقل MCP'], descriptions: ['قراءة الكيانات وإحصاءات الجرد','قراءة الحالات والسمات الحالية','قراءة كيانات الأتمتة وحالتها','قراءة الإعداد وبيانات السجلات','قراءة الخدمات والمخططات المتاحة','قراءة الأحداث المتاحة','قراءة سجل الحالات مع مرشحات اختيارية','قراءة سجلات النشاط مع مرشحات اختيارية','قراءة الأجهزة المسجلة','قراءة المناطق المسجلة','قراءة الطوابق المسجلة','قراءة التسميات المسجلة','قراءة الكيانات وبياناتها الوصفية','قراءة كيانات البرامج النصية','قراءة كيانات المشاهد','قراءة مساعدات الإدخال','قراءة نطاقات التكامل','فحص المستمع المحلي ومصادقة MCP'], packLabels: ['الجرد الأساسي','تشخيص الأتمتة','جاهزية MCP','اكتمال البيانات'], packDescriptions: ['نموذج القراءة والسجلات الأساسية.','الأتمتة وبيانات النشاط.','الموارد المطلوبة لعملاء المراقبة.','تغطية موسعة وأخطاء نقاط النهاية الصريحة.'], status: ['سليم','خطأ','جزئي','جاهز','جارٍ التحميل','غير معروف'] },
};

const traceTranslations: Record<string, Record<string, string>> = {
  de: { traceability: 'Nachverfolgbarkeit', tracePhase: 'Phase', traceTransport: 'Transport', traceStatus: 'Status', traceCommand: 'Befehl', tracePath: 'Pfad', traceAttempts: 'Versuche', technicalDetails: 'Technische Details' },
  pt: { traceability: 'Rastreabilidade', tracePhase: 'Fase', traceTransport: 'Transporte', traceStatus: 'Estado', traceCommand: 'Comando', tracePath: 'Caminho', traceAttempts: 'Tentativas', technicalDetails: 'Detalhes técnicos' },
  it: { traceability: 'Tracciabilità', tracePhase: 'Fase', traceTransport: 'Trasporto', traceStatus: 'Stato', traceCommand: 'Comando', tracePath: 'Percorso', traceAttempts: 'Tentativi', technicalDetails: 'Dettagli tecnici' },
  zh: { traceability: '可追溯性', tracePhase: '阶段', traceTransport: '传输', traceStatus: '状态', traceCommand: '命令', tracePath: '路径', traceAttempts: '尝试次数', technicalDetails: '技术详情' },
  ja: { traceability: 'トレーサビリティ', tracePhase: 'フェーズ', traceTransport: 'トランスポート', traceStatus: 'ステータス', traceCommand: 'コマンド', tracePath: 'パス', traceAttempts: '試行回数', technicalDetails: '技術詳細' },
  ru: { traceability: 'Трассировка', tracePhase: 'Фаза', traceTransport: 'Транспорт', traceStatus: 'Статус', traceCommand: 'Команда', tracePath: 'Путь', traceAttempts: 'Попытки', technicalDetails: 'Технические сведения' },
  hi: { traceability: 'ट्रेसबिलिटी', tracePhase: 'चरण', traceTransport: 'ट्रांसपोर्ट', traceStatus: 'स्थिति', traceCommand: 'कमांड', tracePath: 'पथ', traceAttempts: 'प्रयास', technicalDetails: 'तकनीकी विवरण' },
  ar: { traceability: 'قابلية التتبع', tracePhase: 'المرحلة', traceTransport: 'النقل', traceStatus: 'الحالة', traceCommand: 'الأمر', tracePath: 'المسار', traceAttempts: 'المحاولات', technicalDetails: 'التفاصيل التقنية' },
};

export const DEVELOPMENT_EXTRA_TRANSLATIONS: Record<string, Record<string, string>> = {};
for (const [locale, spec] of Object.entries(specs)) {
  const entries: Record<string, string> = {};
  const devKeys = ['devUpstreamStatus','devEntityPlaceholder','devStartTimePlaceholder','devItems','devMilliseconds','devSchemaChanged','devRegressions','devNotVerifiable','devLocalListener','devHttpHealth','devHttpMcp','devHostPortPublication'];
  devKeys.forEach((key, index) => { entries[key] = spec.dev[index]; });
  names.forEach((name, index) => { entries[`op${name}Label`] = spec.labels[index]; entries[`op${name}Description`] = spec.descriptions[index]; });
  packs.forEach((name, index) => { entries[`pack${name}Label`] = spec.packLabels[index]; entries[`pack${name}Description`] = spec.packDescriptions[index]; });
  ['statusOk','statusError','statusPartial','statusReady','statusLoading','statusUnknown'].forEach((key, index) => { entries[key] = spec.status[index]; });
  Object.assign(entries, traceTranslations[locale]);
  DEVELOPMENT_EXTRA_TRANSLATIONS[locale] = entries;
}
