export const PERMISSION_TABS_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: { permissionsCapabilitiesTab: 'Capabilities', permissionsOperatorServicesTab: 'Operator Services', permissionsCapabilitiesDescription: 'Choose the read and write capabilities available to this credential.', permissionsOperatorServicesDescription: 'Grant only the globally enabled services to this credential.', permissionsObserverWriteDisabled: 'Write capabilities are unavailable while the read-only profile is selected.' },
  es: { permissionsCapabilitiesTab: 'Capabilities', permissionsOperatorServicesTab: 'Operator services', permissionsCapabilitiesDescription: 'Elige las capabilities de lectura y escritura disponibles para esta credencial.', permissionsOperatorServicesDescription: 'Concede únicamente servicios habilitados globalmente a esta credencial.', permissionsObserverWriteDisabled: 'Las capabilities de escritura no están disponibles mientras está seleccionado el perfil de solo lectura.' },
  fr: { permissionsCapabilitiesTab: 'Capabilities', permissionsOperatorServicesTab: 'Services operator', permissionsCapabilitiesDescription: 'Choisissez les capabilities de lecture et d’écriture disponibles pour cet identifiant.', permissionsOperatorServicesDescription: 'Accordez uniquement les services activés globalement à cet identifiant.', permissionsObserverWriteDisabled: 'Les capabilities d’écriture sont indisponibles avec le profil en lecture seule.' },
  de: { permissionsCapabilitiesTab: 'Capabilities', permissionsOperatorServicesTab: 'Operator-Dienste', permissionsCapabilitiesDescription: 'Wählen Sie die Lese- und Schreib-Capabilities für diesen Zugang.', permissionsOperatorServicesDescription: 'Gewähren Sie diesem Zugang nur global aktivierte Dienste.', permissionsObserverWriteDisabled: 'Schreib-Capabilities sind beim Nur-Lesen-Profil nicht verfügbar.' },
  pt: { permissionsCapabilitiesTab: 'Capabilities', permissionsOperatorServicesTab: 'Serviços operator', permissionsCapabilitiesDescription: 'Escolha as capabilities de leitura e escrita disponíveis para esta credencial.', permissionsOperatorServicesDescription: 'Atribua apenas serviços ativados globalmente a esta credencial.', permissionsObserverWriteDisabled: 'As capabilities de escrita não estão disponíveis com o perfil somente leitura.' },
  it: { permissionsCapabilitiesTab: 'Capabilities', permissionsOperatorServicesTab: 'Servizi operator', permissionsCapabilitiesDescription: 'Scegli le capabilities di lettura e scrittura disponibili per questa credenziale.', permissionsOperatorServicesDescription: 'Assegna a questa credenziale solo i servizi abilitati globalmente.', permissionsObserverWriteDisabled: 'Le capabilities di scrittura non sono disponibili con il profilo di sola lettura.' },
  zh: { permissionsCapabilitiesTab: 'Capabilities', permissionsOperatorServicesTab: 'Operator 服务', permissionsCapabilitiesDescription: '选择此凭据可用的读取和写入能力。', permissionsOperatorServicesDescription: '仅向此凭据授予全局启用的服务。', permissionsObserverWriteDisabled: '选择只读配置时，写入能力不可用。' },
  ja: { permissionsCapabilitiesTab: 'Capabilities', permissionsOperatorServicesTab: 'Operator サービス', permissionsCapabilitiesDescription: 'この資格情報で利用できる読み取り・書き込み能力を選択します。', permissionsOperatorServicesDescription: 'グローバルで有効なサービスだけをこの資格情報に付与します。', permissionsObserverWriteDisabled: '読み取り専用プロファイルでは書き込み能力を利用できません。' },
  ru: { permissionsCapabilitiesTab: 'Capabilities', permissionsOperatorServicesTab: 'Сервисы operator', permissionsCapabilitiesDescription: 'Выберите доступные этим учётным данным возможности чтения и записи.', permissionsOperatorServicesDescription: 'Выдавайте только глобально включённые сервисы.', permissionsObserverWriteDisabled: 'Возможности записи недоступны для профиля только для чтения.' },
  hi: { permissionsCapabilitiesTab: 'Capabilities', permissionsOperatorServicesTab: 'Operator सेवाएँ', permissionsCapabilitiesDescription: 'इस credential के लिए उपलब्ध read और write capabilities चुनें।', permissionsOperatorServicesDescription: 'इस credential को केवल globally enabled services grant करें।', permissionsObserverWriteDisabled: 'read-only profile चुने होने पर write capabilities उपलब्ध नहीं हैं।' },
  ar: { permissionsCapabilitiesTab: 'Capabilities', permissionsOperatorServicesTab: 'خدمات Operator', permissionsCapabilitiesDescription: 'اختر إمكانات القراءة والكتابة المتاحة لبيانات الاعتماد هذه.', permissionsOperatorServicesDescription: 'امنح بيانات الاعتماد هذه الخدمات المفعلة عالميًا فقط.', permissionsObserverWriteDisabled: 'إمكانات الكتابة غير متاحة عند اختيار ملف القراءة فقط.' },
};
