export const POLICY_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    operatorServicesTitle: 'Operator services', operatorServicesSubtitle: 'Choose the Home Assistant services that operator credentials may be granted.', operatorServicesNotGrant: 'This is a global permission ceiling. Selecting a service here does not grant it to any client or credential.', operatorServicesGrantHint: 'Grant selected services separately in each client credential.', operatorServicesSummary: 'Global permission ceiling', operatorServicesEnabled: 'services available to grant', operatorServicesDomains: 'domains', operatorServicesClients: 'operator credentials with grants', operatorServicesSelected: 'services enabled', operatorServicesSave: 'Save global ceiling', operatorServicesSaved: 'Global service ceiling saved', operatorServicesChanges: 'Changes apply without restarting the add-on.', operatorServicesUnavailable: 'Home Assistant service catalog unavailable.', operatorServicesNoSelection: 'No operator service can currently be granted.', operatorServicesBlocked: 'Blocked by global policy', operatorServicesAvailable: 'Available to grant', operatorServicesRequiresApproval: 'Every mutation still requires explicit approval.',
  },
  es: {
    operatorServicesTitle: 'Servicios operator', operatorServicesSubtitle: 'Elige los servicios de Home Assistant que podrán concederse a credenciales operator.', operatorServicesNotGrant: 'Este es un límite global de permisos. Seleccionar un servicio aquí no lo concede a ningún cliente ni credencial.', operatorServicesGrantHint: 'Concede los servicios seleccionados por separado en cada credencial de cliente.', operatorServicesSummary: 'Límite global de permisos', operatorServicesEnabled: 'servicios disponibles para conceder', operatorServicesDomains: 'dominios', operatorServicesClients: 'credenciales operator con grants', operatorServicesSelected: 'servicios habilitados', operatorServicesSave: 'Guardar límite global', operatorServicesSaved: 'Límite global de servicios guardado', operatorServicesChanges: 'Los cambios se aplican sin reiniciar el add-on.', operatorServicesUnavailable: 'El catálogo de servicios de Home Assistant no está disponible.', operatorServicesNoSelection: 'Actualmente no se puede conceder ningún servicio operator.', operatorServicesBlocked: 'Bloqueado por la política global', operatorServicesAvailable: 'Disponible para conceder', operatorServicesRequiresApproval: 'Toda mutación sigue requiriendo aprobación explícita.',
  },
  fr: {
    operatorServicesTitle: 'Services operator', operatorServicesSubtitle: 'Choisissez les services Home Assistant pouvant être accordés aux identifiants operator.', operatorServicesNotGrant: 'Il s’agit d’un plafond global de permissions. Sélectionner un service ici ne l’accorde à aucun client ni identifiant.', operatorServicesGrantHint: 'Accordez ensuite les services séparément à chaque identifiant client.', operatorServicesSummary: 'Plafond global des permissions', operatorServicesEnabled: 'services disponibles à accorder', operatorServicesDomains: 'domaines', operatorServicesClients: 'identifiants operator avec des grants', operatorServicesSelected: 'services activés', operatorServicesSave: 'Enregistrer le plafond global', operatorServicesSaved: 'Plafond global des services enregistré', operatorServicesChanges: 'Les changements s’appliquent sans redémarrer l’add-on.', operatorServicesUnavailable: 'Catalogue des services Home Assistant indisponible.', operatorServicesNoSelection: 'Aucun service operator ne peut actuellement être accordé.', operatorServicesBlocked: 'Bloqué par la politique globale', operatorServicesAvailable: 'Disponible à accorder', operatorServicesRequiresApproval: 'Toute mutation nécessite toujours une approbation explicite.',
  },
  de: {
    operatorServicesTitle: 'Operator-Dienste', operatorServicesSubtitle: 'Wählen Sie Home-Assistant-Dienste aus, die Operator-Anmeldedaten erhalten dürfen.', operatorServicesNotGrant: 'Dies ist eine globale Berechtigungsgrenze. Die Auswahl gewährt keinem Client und keiner Anmeldedaten den Dienst.', operatorServicesGrantHint: 'Gewähren Sie ausgewählte Dienste separat in jeder Client-Anmeldedatei.', operatorServicesSummary: 'Globale Berechtigungsgrenze', operatorServicesEnabled: 'Dienste zur Vergabe verfügbar', operatorServicesDomains: 'Domänen', operatorServicesClients: 'Operator-Anmeldedaten mit Grants', operatorServicesSelected: 'Dienste aktiviert', operatorServicesSave: 'Globale Grenze speichern', operatorServicesSaved: 'Globale Dienstgrenze gespeichert', operatorServicesChanges: 'Änderungen gelten ohne Neustart des Add-ons.', operatorServicesUnavailable: 'Home-Assistant-Dienstkatalog nicht verfügbar.', operatorServicesNoSelection: 'Derzeit kann kein Operator-Dienst vergeben werden.', operatorServicesBlocked: 'Durch globale Richtlinie blockiert', operatorServicesAvailable: 'Zur Vergabe verfügbar', operatorServicesRequiresApproval: 'Jede Mutation erfordert weiterhin eine ausdrückliche Genehmigung.',
  },
  pt: {
    operatorServicesTitle: 'Serviços operator', operatorServicesSubtitle: 'Escolha os serviços Home Assistant que podem ser atribuídos a credenciais operator.', operatorServicesNotGrant: 'Este é um limite global de permissões. Selecionar um serviço aqui não o atribui a nenhum cliente ou credencial.', operatorServicesGrantHint: 'Atribua os serviços selecionados separadamente a cada credencial de cliente.', operatorServicesSummary: 'Limite global de permissões', operatorServicesEnabled: 'serviços disponíveis para atribuição', operatorServicesDomains: 'domínios', operatorServicesClients: 'credenciais operator com grants', operatorServicesSelected: 'serviços ativados', operatorServicesSave: 'Guardar limite global', operatorServicesSaved: 'Limite global de serviços guardado', operatorServicesChanges: 'As alterações aplicam-se sem reiniciar o add-on.', operatorServicesUnavailable: 'Catálogo de serviços Home Assistant indisponível.', operatorServicesNoSelection: 'Nenhum serviço operator pode ser atribuído neste momento.', operatorServicesBlocked: 'Bloqueado pela política global', operatorServicesAvailable: 'Disponível para atribuição', operatorServicesRequiresApproval: 'Cada mutação continua a exigir aprovação explícita.',
  },
  it: {
    operatorServicesTitle: 'Servizi operator', operatorServicesSubtitle: 'Scegli i servizi Home Assistant che possono essere assegnati alle credenziali operator.', operatorServicesNotGrant: 'Questo è un limite globale delle autorizzazioni. Selezionare un servizio qui non lo assegna a nessun client o credenziale.', operatorServicesGrantHint: 'Assegna i servizi selezionati separatamente a ogni credenziale client.', operatorServicesSummary: 'Limite globale delle autorizzazioni', operatorServicesEnabled: 'servizi disponibili per l’assegnazione', operatorServicesDomains: 'domini', operatorServicesClients: 'credenziali operator con grant', operatorServicesSelected: 'servizi abilitati', operatorServicesSave: 'Salva limite globale', operatorServicesSaved: 'Limite globale dei servizi salvato', operatorServicesChanges: 'Le modifiche si applicano senza riavviare l’add-on.', operatorServicesUnavailable: 'Catalogo dei servizi Home Assistant non disponibile.', operatorServicesNoSelection: 'Nessun servizio operator può essere assegnato al momento.', operatorServicesBlocked: 'Bloccato dalla politica globale', operatorServicesAvailable: 'Disponibile per l’assegnazione', operatorServicesRequiresApproval: 'Ogni mutazione richiede ancora un’approvazione esplicita.',
  },
  zh: {
    operatorServicesTitle: 'Operator 服务', operatorServicesSubtitle: '选择可授予 operator 凭据的 Home Assistant 服务。', operatorServicesNotGrant: '这是全局权限上限。在此选择服务不会将其授予任何客户端或凭据。', operatorServicesGrantHint: '请在每个客户端凭据中单独授予所选服务。', operatorServicesSummary: '全局权限上限', operatorServicesEnabled: '个服务可供授予', operatorServicesDomains: '个域', operatorServicesClients: '个拥有授权的 operator 凭据', operatorServicesSelected: '个服务已启用', operatorServicesSave: '保存全局上限', operatorServicesSaved: '全局服务上限已保存', operatorServicesChanges: '更改无需重启加载项即可生效。', operatorServicesUnavailable: 'Home Assistant 服务目录不可用。', operatorServicesNoSelection: '当前无法授予任何 operator 服务。', operatorServicesBlocked: '被全局策略阻止', operatorServicesAvailable: '可供授予', operatorServicesRequiresApproval: '每次变更仍需要明确批准。',
  },
  ja: {
    operatorServicesTitle: 'Operator サービス', operatorServicesSubtitle: 'Operator 資格情報に付与できる Home Assistant サービスを選択します。', operatorServicesNotGrant: 'これはグローバルな権限上限です。ここで選択しても、クライアントや資格情報には付与されません。', operatorServicesGrantHint: '選択したサービスは各クライアント資格情報で個別に付与します。', operatorServicesSummary: 'グローバル権限上限', operatorServicesEnabled: '付与可能なサービス', operatorServicesDomains: 'ドメイン', operatorServicesClients: '付与を持つ operator 資格情報', operatorServicesSelected: '有効なサービス', operatorServicesSave: 'グローバル上限を保存', operatorServicesSaved: 'グローバルサービス上限を保存しました', operatorServicesChanges: 'アドオンの再起動なしで反映されます。', operatorServicesUnavailable: 'Home Assistant サービスカタログを利用できません。', operatorServicesNoSelection: '現在付与できる operator サービスはありません。', operatorServicesBlocked: 'グローバルポリシーによりブロック', operatorServicesAvailable: '付与可能', operatorServicesRequiresApproval: 'すべての変更には明示的な承認が必要です。',
  },
  ru: {
    operatorServicesTitle: 'Сервисы operator', operatorServicesSubtitle: 'Выберите сервисы Home Assistant, которые можно выдавать учётным данным operator.', operatorServicesNotGrant: 'Это глобальный предел разрешений. Выбор здесь не выдаёт сервис ни одному клиенту или набору учётных данных.', operatorServicesGrantHint: 'Выдавайте выбранные сервисы отдельно для каждого клиента.', operatorServicesSummary: 'Глобальный предел разрешений', operatorServicesEnabled: 'сервисов доступно для выдачи', operatorServicesDomains: 'домена', operatorServicesClients: 'учётных данных operator с правами', operatorServicesSelected: 'сервисов включено', operatorServicesSave: 'Сохранить глобальный предел', operatorServicesSaved: 'Глобальный предел сервисов сохранён', operatorServicesChanges: 'Изменения применяются без перезапуска дополнения.', operatorServicesUnavailable: 'Каталог сервисов Home Assistant недоступен.', operatorServicesNoSelection: 'Сейчас нельзя выдать ни одного сервиса operator.', operatorServicesBlocked: 'Заблокировано глобальной политикой', operatorServicesAvailable: 'Доступно для выдачи', operatorServicesRequiresApproval: 'Для каждой мутации по-прежнему требуется явное подтверждение.',
  },
  hi: {
    operatorServicesTitle: 'Operator सेवाएँ', operatorServicesSubtitle: 'वे Home Assistant सेवाएँ चुनें जिन्हें operator credentials को दिया जा सकता है।', operatorServicesNotGrant: 'यह वैश्विक permission ceiling है। यहाँ सेवा चुनने से वह किसी client या credential को नहीं मिलती।', operatorServicesGrantHint: 'चयनित सेवाएँ प्रत्येक client credential में अलग से grant करें।', operatorServicesSummary: 'वैश्विक permission ceiling', operatorServicesEnabled: 'grant के लिए उपलब्ध सेवाएँ', operatorServicesDomains: 'डोमेन', operatorServicesClients: 'grant वाली operator credentials', operatorServicesSelected: 'सेवाएँ enabled', operatorServicesSave: 'वैश्विक ceiling सहेजें', operatorServicesSaved: 'वैश्विक service ceiling सहेजी गई', operatorServicesChanges: 'बदलाव add-on restart के बिना लागू होते हैं।', operatorServicesUnavailable: 'Home Assistant service catalog उपलब्ध नहीं है।', operatorServicesNoSelection: 'अभी कोई operator service grant नहीं की जा सकती।', operatorServicesBlocked: 'वैश्विक policy द्वारा blocked', operatorServicesAvailable: 'grant के लिए उपलब्ध', operatorServicesRequiresApproval: 'हर mutation के लिए explicit approval अभी भी आवश्यक है।',
  },
  ar: {
    operatorServicesTitle: 'خدمات operator', operatorServicesSubtitle: 'اختر خدمات Home Assistant التي يمكن منحها لبيانات اعتماد operator.', operatorServicesNotGrant: 'هذا حد عالمي للصلاحيات. اختيار الخدمة هنا لا يمنحها لأي عميل أو بيانات اعتماد.', operatorServicesGrantHint: 'امنح الخدمات المحددة بشكل منفصل لكل بيانات اعتماد للعميل.', operatorServicesSummary: 'الحد العالمي للصلاحيات', operatorServicesEnabled: 'خدمات متاحة للمنح', operatorServicesDomains: 'نطاقات', operatorServicesClients: 'بيانات اعتماد operator لديها منح', operatorServicesSelected: 'خدمات مفعلة', operatorServicesSave: 'حفظ الحد العالمي', operatorServicesSaved: 'تم حفظ الحد العالمي للخدمات', operatorServicesChanges: 'تُطبّق التغييرات من دون إعادة تشغيل الإضافة.', operatorServicesUnavailable: 'كتالوج خدمات Home Assistant غير متاح.', operatorServicesNoSelection: 'لا يمكن منح أي خدمة operator حاليًا.', operatorServicesBlocked: 'محظور بالسياسة العالمية', operatorServicesAvailable: 'متاح للمنح', operatorServicesRequiresApproval: 'لا تزال كل عملية تغيير تتطلب موافقة صريحة.',
  },
};
