export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    ingressTrusted: 'Ingress trusted identity', tokenDigests: 'SHA-256 token digests', readOnlyMcp: 'Read-only MCP', topologyIngress: 'Ingress', topologyGateway: 'Gateway', topologyCore: 'Core', topologyRecorder: 'Recorder', topologyLogbook: 'Logbook', trusted: 'trusted', transport: 'Transport', tool: 'Tool',
    revokeConfirm: 'Revoke client {client}? This cannot be undone.', rotateConfirm: 'Rotate credentials for {client}? The current token will stop working.', displayName: 'Display name', profile: 'Profile', readOnly: 'read-only', capabilities: 'Capabilities', client: 'Client', capability: 'Capability', mutationRequest: 'Mutation request', evaluate: 'Evaluate', time: 'Time', action: 'Action', target: 'Target', decision: 'Decision', outcome: 'Outcome', requestId: 'Request ID',
    errorLoadState: 'Unable to load gateway state', errorIssueClient: 'Unable to issue client', errorRevokeClient: 'Unable to revoke client', errorRotateClient: 'Unable to rotate client', errorDiscovery: 'Unable to load discovery', errorProbe: 'Unable to run development probe', errorProbes: 'Unable to run development probes', errorPack: 'Unable to run development pack', errorAudit: 'Unable to load audit', errorPolicy: 'Unable to evaluate policy', operatorServicesPolicyInvalid: 'Unable to save the Operator service ceiling. Select up to 500 services and verify that every service is still available.', copyProblemReports: 'Copy errors and warnings', problemReports: 'issues',
    policyReadAllowed: 'Read capability present → read allowed', policyMissingDenied: 'Capability missing → denied', policyMutationDenied: 'Observer asks for a change → denied', policyOperatorDisabled: 'Operator services must be enabled globally', topologyUpstream: 'upstream',
  },
  es: {
    ingressTrusted: 'Identidad de confianza de Ingress', tokenDigests: 'Resúmenes de tokens SHA-256', readOnlyMcp: 'MCP de solo lectura', topologyIngress: 'Ingress', topologyGateway: 'Gateway', topologyCore: 'Core', topologyRecorder: 'Recorder', topologyLogbook: 'Logbook', trusted: 'de confianza', transport: 'Transporte', tool: 'Herramienta',
    revokeConfirm: '¿Revocar el cliente {client}? Esta acción no se puede deshacer.', rotateConfirm: '¿Rotar las credenciales de {client}? El token actual dejará de funcionar.', displayName: 'Nombre visible', profile: 'Perfil', readOnly: 'solo lectura', capabilities: 'Capabilities', client: 'Cliente', capability: 'Capability', mutationRequest: 'Solicitud de mutación', evaluate: 'Evaluar', time: 'Hora', action: 'Acción', target: 'Objetivo', decision: 'Decisión', outcome: 'Resultado', requestId: 'ID de solicitud',
    errorLoadState: 'No se ha podido cargar el estado del gateway', errorIssueClient: 'No se ha podido emitir el cliente', errorRevokeClient: 'No se ha podido revocar el cliente', errorRotateClient: 'No se han podido rotar las credenciales', errorDiscovery: 'No se ha podido cargar el descubrimiento', errorProbe: 'No se ha podido ejecutar la prueba', errorProbes: 'No se han podido ejecutar las pruebas', errorPack: 'No se ha podido ejecutar el paquete', errorAudit: 'No se ha podido cargar la auditoría', errorPolicy: 'No se ha podido evaluar la política', operatorServicesPolicyInvalid: 'No se ha podido guardar el límite de servicios Operator. Puedes seleccionar hasta 500 servicios y todos deben seguir disponibles.', copyProblemReports: 'Copiar errores y avisos', problemReports: 'incidencias',
    policyReadAllowed: 'Capability de lectura presente → lectura permitida', policyMissingDenied: 'Capability ausente → acceso denegado', policyMutationDenied: 'Observer solicita un cambio → denegado', policyOperatorDisabled: 'Operator requiere servicios habilitados globalmente', topologyUpstream: 'upstream',
  },
  fr: {
    ingressTrusted: 'Identité de confiance Ingress', tokenDigests: 'Empreintes de tokens SHA-256', readOnlyMcp: 'MCP en lecture seule', topologyIngress: 'Ingress', topologyGateway: 'Gateway', topologyCore: 'Core', topologyRecorder: 'Recorder', topologyLogbook: 'Logbook', trusted: 'de confiance', transport: 'Transport', tool: 'Outil',
    revokeConfirm: 'Révoquer le client {client} ? Cette action est irréversible.', rotateConfirm: 'Faire pivoter les identifiants de {client} ? Le token actuel cessera de fonctionner.', displayName: "Nom d'affichage", profile: 'Profil', readOnly: 'lecture seule', capabilities: 'Capabilities', client: 'Client', capability: 'Capability', mutationRequest: 'Requête de mutation', evaluate: 'Évaluer', time: 'Heure', action: 'Action', target: 'Cible', decision: 'Décision', outcome: 'Résultat', requestId: 'ID de requête',
    errorLoadState: "Impossible de charger l'état du gateway", errorIssueClient: "Impossible d'émettre le client", errorRevokeClient: 'Impossible de révoquer le client', errorRotateClient: 'Impossible de faire pivoter les identifiants', errorDiscovery: 'Impossible de charger la découverte', errorProbe: "Impossible d'exécuter le test", errorProbes: "Impossible d'exécuter les tests", errorPack: "Impossible d'exécuter le pack", errorAudit: "Impossible de charger l'audit", errorPolicy: "Impossible d'évaluer la politique", copyProblemReports: 'Copier les erreurs et avertissements', problemReports: 'incidents',
    policyReadAllowed: 'Capability de lecture → autorisée', policyMissingDenied: 'Capability absente → refusée', policyMutationDenied: 'Mutation observer → refusée', policyOperatorDisabled: 'Operator → désactivé globalement', topologyUpstream: 'upstream',
  },
};
